# Theme settings
remote_theme: daattali/beautiful-jekyll@5.0.0

# Site settings
title: "Placements Interview Xperience"
description: "ISI Kolkata Placements Interview Questions"
baseurl: "" # Leave empty unless you're hosting in a subdirectory
url: "" # Base URL

# Navbar Links
navbar-links:
  Home: "index"
  Companies: "companies"

# Social Links
social-network-links:
  email: "belalahmedsiddiqui8@gmail.com"
  github: "stoicsapien1"
  linkedin: "stoicsapien1"
