# Theme settings
remote_theme: daattali/beautiful-jekyll@5.0.0

# Site settings
title: "Placement Interview"
description: "ISI Kolkata Placement Interview Questions"
baseurl: "" # Leave empty unless you're hosting in a subdirectory
url: "" # Base URL

# Navbar Links
navbar-links:
  - title: "Home"
    url: "/"
  - title: "Companies"
    url: "/companies"

# Social Links
social-network-links:
  email: "belalahmedsiddiqui8@gmail.com"
  github: "stoicsapien1"
  linkedin: "stoicsapien1"

# Optional: Author information
author:
  name: "Belal Ahmed Siddiqui"
