
remote_theme: daattali/beautiful-jekyll@5.0.0


title: "ISI Placements Xperience"
description: "ISI Kolkata Placements Interview Questions"
baseurl: ""
url: "https://isikolkataplacements.github.io" # Base URL


author: Belal Ahmed Siddiqui

navbar-links:
  Home: "index"
  Companies: "companies"
  About Us: "aboutus"


social-network-links:
  email: "belalahmedsiddiqui8@gmail.com"
  github: "stoicsapien1"
  linkedin: "stoicsapien1"


show_author_info_on_posts: true
